fix: session update and company form submitting issue
opencapco/opencap.co pull request #161
Opened 2024-03-03 14:26 UTC by anikdhabal

2024-03-04 13:33 UTC, G3root requested changes
Great find @anikdhabal ❤️ . currently blocking until #167 is figured out because it touches some code in company-form.

2024-03-04 13:37 UTC, G3root commented on src/server/auth.ts
> -
we have to pass the profile picture url through jwt callback and session callback.

2024-03-05 02:49 UTC, anikdhabal commented
> Great find @anikdhabal ❤️ . currently blocking until #167 is figured out because it touches some code in company-form.

Thanks Nafeez for the review.

2024-03-05 04:19 UTC, dahal requested changes
@anikdhabal @G3root #167 PR is merged. Please resolve the merge conflict and make necessary changes. It looks good to me and huge props to @anikdhabal for identifying the issue and taking the initiative to resolve it.

2024-03-07 04:23 UTC, dahal requested changes
Company create or update flow seems to be broken? Please take a look at this, its not sending a TRPC request.


![company-create-update-flow](https://github.com/opencapco/opencap.co/assets/3684236/8ce30d9f-47fd-4d03-89be-2ff51624f12e)

2024-03-07 04:31 UTC, anikdhabal commented
> Company create or update flow seems to be broken? Please take a look at this, its not sending a TRPC request.
> 
> ![company-create-update-flow](https://private-user-images.githubusercontent.com/3684236/310745460-8ce30d9f-47fd-4d03-89be-2ff51624f12e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODYwNTgsIm5iZiI6MTcwOTc4NTc1OCwicGF0aCI6Ii8zNjg0MjM2LzMxMDc0NTQ2MC04Y2UzMGQ5Zi00N2ZkLTRkMDMtODliZS0yZmY1MTYyNGYxMmUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDQyOTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTA1ZDA1MDYzMWZlNzQ3YTRiNDc1ZDNjNjM3OGY5OTNjMGQwNjZmYWExZmE2YjVjNGI5NWY0N2Q0M2Q4OGI1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aHuf96tlvnfpCgcZjrLtiWmEFKEdRGATd9b8OT-zo7o) [ ![company-create-update-flow](https://private-user-images.githubusercontent.com/3684236/310745460-8ce30d9f-47fd-4d03-89be-2ff51624f12e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODYwNTgsIm5iZiI6MTcwOTc4NTc1OCwicGF0aCI6Ii8zNjg0MjM2LzMxMDc0NTQ2MC04Y2UzMGQ5Zi00N2ZkLTRkMDMtODliZS0yZmY1MTYyNGYxMmUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDQyOTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTA1ZDA1MDYzMWZlNzQ3YTRiNDc1ZDNjNjM3OGY5OTNjMGQwNjZmYWExZmE2YjVjNGI5NWY0N2Q0M2Q4OGI1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aHuf96tlvnfpCgcZjrLtiWmEFKEdRGATd9b8OT-zo7o) ](https://private-user-images.githubusercontent.com/3684236/310745460-8ce30d9f-47fd-4d03-89be-2ff51624f12e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODYwNTgsIm5iZiI6MTcwOTc4NTc1OCwicGF0aCI6Ii8zNjg0MjM2LzMxMDc0NTQ2MC04Y2UzMGQ5Zi00N2ZkLTRkMDMtODliZS0yZmY1MTYyNGYxMmUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDQyOTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTA1ZDA1MDYzMWZlNzQ3YTRiNDc1ZDNjNjM3OGY5OTNjMGQwNjZmYWExZmE2YjVjNGI5NWY0N2Q0M2Q4OGI1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aHuf96tlvnfpCgcZjrLtiWmEFKEdRGATd9b8OT-zo7o) [ ](https://private-user-images.githubusercontent.com/3684236/310745460-8ce30d9f-47fd-4d03-89be-2ff51624f12e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3ODYwNTgsIm5iZiI6MTcwOTc4NTc1OCwicGF0aCI6Ii8zNjg0MjM2LzMxMDc0NTQ2MC04Y2UzMGQ5Zi00N2ZkLTRkMDMtODliZS0yZmY1MTYyNGYxMmUuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDdUMDQyOTE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTA1ZDA1MDYzMWZlNzQ3YTRiNDc1ZDNjNjM3OGY5OTNjMGQwNjZmYWExZmE2YjVjNGI5NWY0N2Q0M2Q4OGI1YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aHuf96tlvnfpCgcZjrLtiWmEFKEdRGATd9b8OT-zo7o)

Yeah, this PR fixed that issue as well. I also explained in detail why the form is not submitting.

2024-03-07 04:53 UTC, dahal commented
> > Company create or update flow seems to be broken? Please take a look at this, its not sending a TRPC request.
> 
> Yeah, this PR fixed that issue as well. I also explained in detail why the form is not submitting.

I was testing it on your current PR, also made sure I have the latest commits, still the same issue.

2024-03-07 08:05 UTC, anikdhabal commented
> > > Company create or update flow seems to be broken? Please take a look at this, its not sending a TRPC request.
> > 
> > 
> > Yeah, this PR fixed that issue as well. I also explained in detail why the form is not submitting.
> 
> I was testing it on your current PR, also made sure I have the latest commits, still the same issue.

Thanks puru, I've updated the code. Now Everything is Ok.

2024-03-08 06:33 UTC, merged