feat: setup email templates
opencapco/opencap.co pull request #26
Opened 2024-01-13 09:37 UTC by G3root

fixes: #25

todo

- [ ] invite template

2024-01-13 16:52 UTC, tedspare commented on src/emails/MemberInviteEmail.tsx
> +                className="rounded bg-[#000000] px-5 py-3 text-center text-[12px] font-semibold text-white no-underline"
`bg-[#000000]` → `bg-black` if possible

2024-01-13 16:52 UTC, tedspare commented on src/emails/MemberInviteEmail.tsx
> +            <Hr className="mx-0 my-[26px] w-full border border-solid border-[#eaeaea]" />
`border-[#eaeaea]` → `border-neutral-200` if possible

2024-01-13 16:54 UTC, tedspare commented on src/server/auth.ts
> +        });
Super clean, nice work

2024-01-13 16:57 UTC, tedspare commented on src/emails/MagicLinkEmail.tsx
> +        <Link href="https://opencap.co/" style={reportLink}>
`"https://opencap.co/"` → `constants.url`

and

`import { constants } from "@/lib/constants";`

2024-01-13 16:58 UTC, tedspare commented on src/emails/MagicLinkEmail.tsx
> +  magicLink: "https://opencap.co/",
Same here, `constants.url`

2024-01-13 17:03 UTC, tedspare approved these changes
LGTM, awesome work Nafees 🚢

Only nitpick: could you match the login button color to the others?

Tested locally with `bun run email:preview` and it looks great. The JSX email preview feature is nice too:

<img width="1299" alt="image" src="https://github.com/opencapco/opencap.co/assets/36117635/569f564b-590d-4fc3-a92e-2ddf47d32342">

<img width="1299" alt="image" src="https://github.com/opencapco/opencap.co/assets/36117635/8fede9f3-77c7-468c-84d0-fc7e2e24ebbd">

2024-01-14 01:36 UTC, dahal commented on src/emails/MagicLinkEmail.tsx
> +const main = {
Can we use tailwind here as well, pretty please 🙏🏼

2024-01-14 01:39 UTC, dahal requested changes
Can we use tailwind on [MagicLinkEmail.tsx](https://github.com/opencapco/opencap.co/pull/26/files#diff-694507ba4413b6d7878fd7a918b3c7449ee85dce33b5caf68f6979a6467340e2) as well 🙏🏼

2024-01-14 01:58 UTC, G3root commented
pushed the nits and requested changes

![Screenshot 2024-01-14 at 07-24-26 JSX email • Member Invite Email](https://github.com/opencapco/opencap.co/assets/84864519/54ed7817-1772-4361-9e5d-ed46380e35d9)

2024-01-14 02:12 UTC, dahal commented
> pushed the nits and requested changes
> 
> ![Screenshot 2024-01-14 at 07-24-26 JSX email • Member Invite Email](https://private-user-images.githubusercontent.com/84864519/296525376-54ed7817-1772-4361-9e5d-ed46380e35d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUxOTg1ODYsIm5iZiI6MTcwNTE5ODI4NiwicGF0aCI6Ii84NDg2NDUxOS8yOTY1MjUzNzYtNTRlZDc4MTctMTc3Mi00MzYxLTllNWQtZWQ0NjM4MGUzNWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE0VDAyMTEyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYWQ2MTYxMDk1MDE5N2JiZjQxNzkwNjc0NDM1Nzg5ZDc3MjY1NjQxMDQyZTgxZTQ5NmZjMmRmOTNlNDI0M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2yWjf0UmG-UEG8Z7DQ65HnPPrHEMKqt5-j1_uTESaPg)

Lets have same button as invite email (black). Its good to after that. Impressive work, as always @G3root 👏🏼

2024-01-14 02:36 UTC, G3root commented
@dahal  Done. I read the comment the other way around. 😸 

![Screenshot 2024-01-14 at 08-03-12 JSX email • Magic Link Email](https://github.com/opencapco/opencap.co/assets/84864519/ee10aa2a-9d72-44c4-ab34-ea23e01d21c0)

2024-01-14 06:49 UTC, merged