feat: track events with audit logs
opencapco/opencap.co pull request #92
Opened 2024-02-03 09:34 UTC by G3root

fixes #90

2024-02-04 09:14 UTC, G3root commented
known issues 

- `stakeholder.invite` and `stakeholder.remove` has invitee's name to be undefined should be fixed after #79

2024-02-05 06:39 UTC, dahal commented
> known issues
> 
> * `stakeholder.invite` action and `stakeholder.remove` action while revoking invite has undefined value. it should be fixed after [Improve stakeholder invite flow #79](https://github.com/opencapco/opencap.co/issues/79)

@G3root I don't think #79 will fix it. Lets create an issue for this.

2024-02-05 07:42 UTC, dahal requested changes
Everything looks great @G3root , I have left a comment, else its good to go.

2024-02-05 07:42 UTC, dahal commented on src/server/audit/actions.ts
> +    "activate",
Let's keep these events/actions consistent, lets go with `signed-up`, `invited`, `re-invited`, `accepted`. 

Note: these events has already occurred, it only makes sense to stick with past tense.

2024-02-06 03:12 UTC, merged